# authors: nanak <2152598815@qq.com>
# github <github.com/jiuyue112>
# update: 2023-07-15

version: "3"
services:
    weba:
        build: ./web
        expose:
            - 80
    webb:
        build: ./web
        expose:
            - 80
    webc:
        build: ./web
        expose:
            - 80
    haproxy:
        image: haproxy:2.8
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        external_links:
            - weba
            - webb
            - webc
        ports:
            - "80:80"
            - "70:70" # haproxy admin console, login with user:pass
